---
networks:
  default:
    name: arr
  traefik:
    external: true
services:
# filebrowser
  filebrowser:
    networks:
      - traefik
    volumes:
      - /var/srv:/srv
      - /var/srv/filebrowser/filebrowser.db:/database/filebrowser.db
      - /var/srv/filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 127.0.0.1:8080:80
    image: filebrowser/filebrowser:s6
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser.entrypoints=web
      - "traefik.http.routers.filebrowser.rule=HostRegexp(`^filebrowser${TRAEFIK_RULE_SUFFIX}"
      - traefik.http.services.filebrowser.loadbalancer.server.port=80
# plex
  plex:
    environment:
      - TZ=${TZ}
      - VERSION=latest
    volumes:
      - type: bind
        source: /var/srv/media
        target: /media
        bind:
          create_host_path: false
      # - type: bind
      #   source: /var/srv/media/content/tv
      #   target: /tv
      #   bind:
      #     create_host_path: false
      # - type: bind
      #   source: /var/srv/media/content/movies
      #   target: /movies
      #   bind:
      #     create_host_path: false
      - type: bind
        source: /var/srv/apps/plex/data
        target: /config
        bind:
          create_host_path: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=HostRegexp(`^plex${TRAEFIK_RULE_SUFFIX}"
      - traefik.http.services.plex.loadbalancer.server.port=32400

    restart: unless-stopped

# Arr stack
  prowlarr:
    networks:
      - default
      - traefik
    environment:
      - TZ=${TZ}
    volumes:
      - type: bind
        source: /var/srv/apps/prowlarr/data
        target: /config
        bind:
          create_host_path: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.prowlarr.rule=HostRegexp(`^prowlarr${TRAEFIK_RULE_SUFFIX}"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
  radarr:
    networks:
      - default
      - traefik
    environment:
      - TZ=${TZ}
    volumes: !override
      - type: bind
        source: /var/srv/media
        target: /media
        bind:
          create_host_path: false
      - type: bind
        source: /var/srv/apps/radarr/data
        target: /config
        bind:
          create_host_path: true
      # - type: bind
      #   source: /var/srv/media/content/movies
      #   target: /movies
      #   bind:
      #     create_host_path: false
      # - type: bind
      #   source: /var/srv/media/downloads
      #   target: /downloads
      #   bind:
      #     create_host_path: false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_DOCKER_NETWORK}"
      - "traefik.http.routers.radarr.rule=HostRegexp(`^radarr${TRAEFIK_RULE_SUFFIX}"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
  sonarr:
    networks:
      - default
      - traefik
    environment:
      - TZ=${TZ}
    volumes: !override
      - type: bind
        source: /var/srv/media
        target: /media
        bind:
          create_host_path: false
      - type: bind
        source: /var/srv/apps/sonarr/data
        target: /config
        bind:
          create_host_path: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.sonarr.rule=HostRegexp(`^sonarr${TRAEFIK_RULE_SUFFIX}"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  qbittorrent:
      environment:
        - TZ=America/New_York
        - WEBUI_PORT=8112
        - TORRENTING_PORT=51412
      volumes: !override
        - type: bind
          source: /var/srv/apps/qbittorrent/appdata
          target: /config
          bind:
            create_host_path: true
        - type: bind
          source: /var/srv/media/downloads
          target: /downloads
          bind:
            create_host_path: true
        - type: bind
          source: /var/srv/media
          target: /media
          bind:
            create_host_path: true
      network_mode: host
      labels:
        - traefik.enable=true
        - "traefik.http.routers.qbittorrent.rule=HostRegexp(`^qbittorrent${TRAEFIK_RULE_SUFFIX}"
        - traefik.http.services.qbittorrent.loadbalancer.server.port=8112
      restart: unless-stopped
