---
x-base:
  name: &name radarr
networks:
  default:
    name: *name
  traefik:
    external: true
services:
  radarr:
    env_file:
#      - path: ./default.env
#        required: true
      - path: ./override.env
        required: false
    networks:
      - default
      - traefik
    environment:
      - TZ=America/New_York
    volumes:
      - type: bind
        source: /var/srv/apps/${APP_NAME}/data
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: /var/srv/media/plex/movies
        target: /movies
        bind:
          create_host_path: false
      - type: bind
        source: /var/srv/media/downloads
        target: /downloads
        bind:
          create_host_path: false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${APP_NAME}.rule=HostRegexp(`^${APP_NAME}\\.${TRAEFIK_HOSTNAME}(?:\\..*)*$$`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=7878"
